_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 84
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 84
                - 98
            "3":
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.4
            "6": 4.48.0
            "8":
                - 5
            "12": 0.19.4
            "13": linux-x86_64
trl_ppo_trainer_config:
    value:
        adap_kl_ctrl: true
        backward_batch_size: 8
        batch_size: 8
        cliprange: 0.2
        cliprange_value: 0.2
        compare_steps: 1
        dataset_num_proc: null
        early_stopping: false
        exp_name: rl_training
        forward_batch_size: null
        gamma: 1
        global_backward_batch_size: 8
        global_batch_size: 8
        gradient_accumulation_steps: 8
        gradient_checkpointing: false
        horizon: 10000
        init_kl_coef: 0.2
        is_encoder_decoder: false
        is_peft_model: true
        kl_penalty: kl
        lam: 0.95
        learning_rate: 1.4e-05
        log_with: wandb
        max_grad_norm: null
        mini_batch_size: 1
        model_name: /home/exouser/Desktop/0_ModelCheckpoint/Full_RL_Model/CheckPoint_500
        optimize_cuda_cache: true
        optimize_device_cache: false
        ppo_epochs: 4
        query_dataset: stanfordnlp/imdb
        ratio_threshold: 10
        remove_unused_columns: true
        reward_model: sentiment-analysis:lvwerra/distilbert-imdb
        score_clip: null
        seed: 0
        steps: 720
        target: 6
        target_kl: 0.15
        task_name: null
        total_ppo_epochs: 90
        tracker_project_name: trl
        use_score_norm: false
        use_score_scaling: false
        vf_coef: 0.1
        whiten_rewards: false
        world_size: 1
